### ISSUE TITLE
Image upload fails with the Brave browser

### ISSUE THREAD

**Issue by olistik** [ello/webapp#338]
```gherkin
As a logged user on the Brave browser, version "0.19.53" and rev "e09025b"
When I go to "https://ello.co/settings"
And I click "Upload Avatar"
And I choose a "360x360" jpg file
Then nothing happens in the UI
And web inspector shows the Javascript error `Uncaught TypeError: Cannot read property 'split' of undefined at Image.u.onload (file_helper.js:147)`
```

![screen shot 2017-10-19 at 14 36 03](https://user-images.githubusercontent.com/21038/31771439-73708382-b4dc-11e7-84ec-829a48c1e9c3.png)

[Brave browser](https://brave.com/)

If I use the latest Google Chrome (Version 61.0.3163.100 (Official Build) (64-bit)), everything works just fine.

**Comment by olistik** [comment]
I tried to upload an image within the context of a new post and the same problem happens.

**Comment by alanpeabody** [comment]
Thanks for the report @olistik. Unfortunately we don't officially support anything but the 2 most recent versions of the major browsers (edge, firefox, chrome).

That said, I just downloaded the most recent Brave for OSX and had no issue. What OS are you running?

I don't know much about Brave, but our uploads go directly to S3. That could potentially get blocked by Brave - can it be whitelisted?

**Comment by olistik** [comment]
@alanpeabody thanks for the quick reply.
I figured it out: the problem is due to a specific feature of Brave, called "Fingerprinting Protection". I disabled it and image upload worked as expected.

![screen shot 2017-10-19 at 16 55 10](https://user-images.githubusercontent.com/21038/31777486-734371d2-b4ee-11e7-96fe-51fb34ae8aaf.png)

I think I can safely close the issue :-)
Thanks again

**Comment by alanpeabody** [comment]
@olistik great, thanks!
